name: CI/CD for Development Branches

on:
  push:
    branches:
      - dev
      - dev/**  # subbranches like dev/alex, dev/jamie, etc.

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          pip install -r odoo/requirements.txt

      - name: Run unit tests
        run: |
          pytest  # of je specifieke testcommando

  deploy:
    needs: test
    runs-on: ubuntu-latest
    if: success() && startsWith(github.ref, 'refs/heads/dev')  # Alleen main dev branch pushed to server
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USER }}
          password: ${{ secrets.DOCKER_KEY }}

      - name: Build and push Docker image
        run: |
          docker build -t ${{ secrets.DOCKER_USER }}/attendify_pos:latest -f odoo/Dockerfile .
          docker push ${{ secrets.DOCKER_USER }}/attendify_pos:latest

      - name: SSH and deploy
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          password: ${{ secrets.SSH_PASSWORD }}
          port: 30030
          script: |
            cd ~/attendify/POS
            git fetch --all
            git reset --hard origin/dev
            docker-compose pull
            docker-compose up -d --build --remove-orphans
