name: Unit Tests

on:
  push:
    branches: [dev]

jobs:
  unit-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          pip install -r odoo/requirements.txt

      - name: Run unit tests
        run: pytest tests/unit/
